<eclipse>
<message date="1/1/2000" time="0.00000000000000">
 CHECKING FOR LICENSES                                                   
</message>
<message date="1/1/2000" time="0.00000000000000">
 CHECKING FOR LICENSES                                                   
</message>
<message date="1/1/2000" time="0.00000000000000">
 THE MEMORY REQUIRED TO PROCESS THE GRID SECTION IS                      
      17002 KBYTES                                                       
</message>
<warning date="1/1/2000" time="0.00000000000000">
 INCLUDED FILE APPEARS TO BE A GRID FILE                                 
 GRID FILES MUST BE IMPORTED USING GDFILE OR IMPORT                      
</warning>
<warning date="1/1/2000" time="0.00000000000000">
 FLUX FLAG SET IN RUNSPEC BUT FLUXNUM KEYWORD                            
 NOT USED -- SAVE SPACE BY SETTING NTFREG = 0                            
 IN RUNSPEC KEYWORD REGDIMS.                                             
</warning>
<message date="1/1/2000" time="0.00000000000000">
 NEITHER OLDTRAN,OLDTRANR NOR NEWTRAN SPECIFIED                          
 TRANSMISSIBILITIES TO BE CALCULATED                                     
 USING  NEWTRAN                                                          
</message>
<message date="1/1/2000" time="0.00000000000000">
        3 PINCH-OUT CONNECTIONS GENERATED                                
</message>
<message date="1/1/2000" time="0.00000000000000">
 PRE-PROCESSING HAS FOUND 3 NON-NEIGHBOUR CONNECTIONS                    
 WHICH EITHER JOIN ADJACENT CELLS OR CAN BE TREATED AS A                 
 NORMAL CONNECTION. THE TRANSMISSIBILITY HAS BEEN ADDED TO               
 THE APPROPRIATE CELL TRANSMISSIBILITY AND THE                           
 NON-NEIGHBOUR CONNECTION REMOVED FROM THE SIMULATION                    
</message>
<message date="1/1/2000" time="0.00000000000000">
 A FULL LISTING OF THESE NNCS CAN BE OBTAINED BY SETTING                 
 THE ALLNNC MNEMONIC IN RPTGRID. THE OUTPUT HAS THE                      
 TITLE MNEMONIC DEL-NNC                                                  
</message>
<message date="1/1/2000" time="0.00000000000000">
      176 NON-NEIGHBOUR CONNECTIONS HAVE BEEN IGNORED                    
 AS THEIR TRANSMISSIBILITY IS LESS THAN 0.100000E-05                     
</message>
<message date="1/1/2000" time="0.00000000000000">
 3023 NON-NEIGHBOUR CONNECTIONS PRESENT                                  
</message>
<comment date="1/1/2000" time="0.00000000000000">
 LEFT HANDED GRIDS MAY NOT BE SUPPORTED                                  
  IN ALL PRE AND POST PROCESSORS                                         
</comment>
<comment date="1/1/2000" time="0.00000000000000">
 THE GRID APPEARS TO BE LEFT HANDED, BUT                                 
 IS SPECIFIED IN GDORIENT AS RIGHT HANDED.                               
 ENSURE GDORIENT IS CORRECTLY DEFINED.                                   
</comment>
<message date="1/1/2000" time="0.00000000000000">
 NUMBER OF ACTIVE CELLS IS 35823                                         
</message>
<message date="1/1/2000" time="0.00000000000000">
 THE MEMORY REQUIRED TO PROCESS THE SOLUTION SECTION IS                  
     631485 KBYTES                                                       
</message>
<message date="1/1/2000" time="0.00000000000000">
    89918 CHARACTER VARIABLES USED                                       
</message>
<warning date="1/1/2000" time="0.00000000000000">
 ALTHOUGH ROCK DATA WAS ASSOCIATED WITH ROCKNUM                          
 THE NUMBER OF REGIONS WAS NOT EXPLICITLY SET                            
 USING ARGUMENT 13 OF KEYWORD TABDIMS                                    
 ROCK WILL BE ASSOCIATED WITH PVTNUM INSTEAD                             
</warning>
<warning date="1/1/2000" time="0.00000000000000">
 THE PROCESSED PVTO DATA FOR TABLE   1                                   
 HAS UNDERSATURATED BO LINES THAT WILL INTERSECT                         
 IF EXTRAPOLATED                                                         
 AT RS VALUES OF     522.8400  SM3/SM3 AND     630.0000  SM3/SM3         
 AND A PRESSURE OF       745.57   BARSA                                  
</warning>
<warning date="1/1/2000" time="0.00000000000000">
 THE PROCESSED PVTO DATA FOR TABLE   1                                   
 HAS UNDERSATURATED BO LINES THAT WILL INTERSECT                         
 IF EXTRAPOLATED                                                         
 AT RS VALUES OF     522.8400  SM3/SM3 AND     630.0000  SM3/SM3         
 AND A PRESSURE OF       745.99   BARSA                                  
</warning>
<warning date="1/1/2000" time="0.00000000000000">
 THE MAXIMUM PRESSURE ENTERED IN THE PVT TABLES                          
 FOR THE OIL PHASE IS    700.100. THIS IS GREATER THAN                   
 THE MAXIMUM PRESSURE FOR THE GAS PHASE,    700.000                      
 AND MAY LEAD TO PVT TABLE EXTRAPOLATION                                 
</warning>
<message date="1/1/2000" time="0.00000000000000">
 SAVE FILE HAS BEEN WRITTEN.                                             
</message>
<warning date="1/1/2000" time="0.00000000000000">
 THE FINE GRID BLOCK EQUILIBRATION SHOULD NOT                            
 USUALLY BE USED WITH THE SWATINIT KEYWORD AS                            
 THE INTEGRATED SOLUTION WILL NOT IN GENERAL                             
 HONOUR THE SWATINIT DATA.                                               
 FOR EQUILIBRATION REGION 1                                              
</warning>
<warning date="1/1/2000" time="0.00000000000000">
 THE FINE GRID BLOCK EQUILIBRATION SHOULD NOT                            
 USUALLY BE USED WITH THE SWATINIT KEYWORD AS                            
 THE INTEGRATED SOLUTION WILL NOT IN GENERAL                             
 HONOUR THE SWATINIT DATA.                                               
 FOR EQUILIBRATION REGION 2                                              
</warning>
<message date="1/1/2000" time="0.00000000000000">
 DRSDT OR DRSDTR KEYWORDS HAVE NOT BEEN                                  
 ENTERED, SO THE MAXIMUM GAS RE-SOLUTION                                 
 RATE IS DEFAULTED TO INFINITY.                                          
</message>
<message date="1/1/2000" time="0.00000000000000">
 RESTART FILE WRITTEN   REPORT     0                                     
 RESTART INCLUDES FLUIDS IN PLACE                                        
</message>
<message date="1/2/2000" time="31.00000000000000">
 OPENING WELL OP_1     AT TIME     31.00   DAYS                          
 CONTROLLED BY RESERVOIR FLUID VOLUME RATE                               
</message>
<message date="1/2/2000" time="31.00000000000000">
 OPENING WELL OP_2     AT TIME     31.00   DAYS                          
 CONTROLLED BY RESERVOIR FLUID VOLUME RATE                               
</message>
<message date="1/2/2000" time="31.00000000000000">
 OPENING WELL OP_3     AT TIME     31.00   DAYS                          
 CONTROLLED BY RESERVOIR FLUID VOLUME RATE                               
</message>
<message date="1/2/2000" time="31.00000000000000">
 OPENING WELL WI_1     AT TIME     31.00   DAYS                          
 CONTROLLED BY WATER RATE                                                
</message>
<problem date="1/2/2000" time="31.00000000000000">
 POTENTIAL IN WELL OP_1     NOT CONVERGED IN  1 X  50 ITERATIONS         
 RESIDUAL ERROR IN FLOWS AND PRESSURE                                    
   OIL         8.38125E+02                                               
   WATER       2.95269E-02                                               
   GAS         1.54215E+05                                               
  MSW PRES     1.50844E+02                                               
 TRY SETTING ITEM 2 IN THE WPOTCALC KEYWORD.                             
 TRY CHANGING PARAMETERS IN THE WSEGITER KEYWORD                         
</problem>
<problem date="1/2/2000" time="31.00000000000000">
 POTENTIAL IN WELL OP_3     NOT CONVERGED IN  1 X  50 ITERATIONS         
 RESIDUAL ERROR IN FLOWS AND PRESSURE                                    
   OIL         1.53579E+04                                               
   WATER       1.49915E+05                                               
   GAS         3.63645E+05                                               
  MSW PRES     1.21667E+02                                               
 TRY SETTING ITEM 2 IN THE WPOTCALC KEYWORD.                             
 TRY CHANGING PARAMETERS IN THE WSEGITER KEYWORD                         
</problem>
<problem date="2/2/2000" time="32.00000000000000">
 POTENTIAL IN WELL OP_1     NOT CONVERGED IN  1 X  50 ITERATIONS         
 RESIDUAL ERROR IN FLOWS AND PRESSURE                                    
   OIL         1.23062E+03                                               
   WATER       2.22158E-02                                               
   GAS         2.26435E+05                                               
  MSW PRES     1.32272E+02                                               
 TRY SETTING ITEM 2 IN THE WPOTCALC KEYWORD.                             
 TRY CHANGING PARAMETERS IN THE WSEGITER KEYWORD                         
</problem>
<problem date="4/2/2000" time="34.31864251793397">
 POTENTIAL IN WELL OP_1     NOT CONVERGED IN  1 X  50 ITERATIONS         
 RESIDUAL ERROR IN FLOWS AND PRESSURE                                    
   OIL         6.99005E+02                                               
   WATER       1.23977E-02                                               
   GAS         1.28617E+05                                               
  MSW PRES     1.36953E+02                                               
 TRY SETTING ITEM 2 IN THE WPOTCALC KEYWORD.                             
 TRY CHANGING PARAMETERS IN THE WSEGITER KEYWORD                         
</problem>
<problem date="9/2/2000" time="39.31864251793397">
 POTENTIAL IN WELL OP_1     NOT CONVERGED IN  1 X  50 ITERATIONS         
 RESIDUAL ERROR IN FLOWS AND PRESSURE                                    
   OIL         1.52043E+03                                               
   WATER       2.27763E-02                                               
   GAS         2.79758E+05                                               
  MSW PRES     1.08082E+02                                               
 TRY SETTING ITEM 2 IN THE WPOTCALC KEYWORD.                             
 TRY CHANGING PARAMETERS IN THE WSEGITER KEYWORD                         
</problem>
<problem date="14/2/2000" time="44.31864251793397">
 POTENTIAL IN WELL OP_1     NOT CONVERGED IN  1 X  50 ITERATIONS         
 RESIDUAL ERROR IN FLOWS AND PRESSURE                                    
   OIL         1.51054E+03                                               
   WATER       2.33675E-02                                               
   GAS         2.77939E+05                                               
  MSW PRES     1.07554E+02                                               
 TRY SETTING ITEM 2 IN THE WPOTCALC KEYWORD.                             
 TRY CHANGING PARAMETERS IN THE WSEGITER KEYWORD                         
</problem>
<problem date="19/2/2000" time="49.31864251793397">
 POTENTIAL IN WELL OP_1     NOT CONVERGED IN  1 X  50 ITERATIONS         
 RESIDUAL ERROR IN FLOWS AND PRESSURE                                    
   OIL         1.50136E+03                                               
   WATER       2.38952E-02                                               
   GAS         2.76250E+05                                               
  MSW PRES     1.07094E+02                                               
 TRY SETTING ITEM 2 IN THE WPOTCALC KEYWORD.                             
 TRY CHANGING PARAMETERS IN THE WSEGITER KEYWORD                         
</problem>
<problem date="24/2/2000" time="54.31864251793397">
 POTENTIAL IN WELL OP_1     NOT CONVERGED IN  1 X  50 ITERATIONS         
 RESIDUAL ERROR IN FLOWS AND PRESSURE                                    
   OIL         1.41717E+03                                               
   WATER       2.53577E-02                                               
   GAS         2.60760E+05                                               
  MSW PRES     1.16605E+02                                               
 TRY SETTING ITEM 2 IN THE WPOTCALC KEYWORD.                             
 TRY CHANGING PARAMETERS IN THE WSEGITER KEYWORD                         
</problem>
<problem date="27/2/2000" time="57.15932125896698">
 POTENTIAL IN WELL OP_1     NOT CONVERGED IN  1 X  50 ITERATIONS         
 RESIDUAL ERROR IN FLOWS AND PRESSURE                                    
   OIL         1.41071E+03                                               
   WATER       2.55880E-02                                               
   GAS         2.59571E+05                                               
  MSW PRES     1.16549E+02                                               
 TRY SETTING ITEM 2 IN THE WPOTCALC KEYWORD.                             
 TRY CHANGING PARAMETERS IN THE WSEGITER KEYWORD                         
</problem>
<problem date="1/3/2000" time="60.00000000000000">
 POTENTIAL IN WELL OP_1     NOT CONVERGED IN  1 X  50 ITERATIONS         
 RESIDUAL ERROR IN FLOWS AND PRESSURE                                    
   OIL         1.79491E+03                                               
   WATER       4.39982E-02                                               
   GAS         3.30263E+05                                               
  MSW PRES     1.46156E+02                                               
 TRY SETTING ITEM 2 IN THE WPOTCALC KEYWORD.                             
 TRY CHANGING PARAMETERS IN THE WSEGITER KEYWORD                         
</problem>
<problem date="2/3/2000" time="61.00000000000000">
 POTENTIAL IN WELL OP_1     NOT CONVERGED IN  1 X  50 ITERATIONS         
 RESIDUAL ERROR IN FLOWS AND PRESSURE                                    
   OIL         6.61144E+02                                               
   WATER       1.62483E-02                                               
   GAS         1.21651E+05                                               
  MSW PRES     1.57109E+02                                               
 TRY SETTING ITEM 2 IN THE WPOTCALC KEYWORD.                             
 TRY CHANGING PARAMETERS IN THE WSEGITER KEYWORD                         
</problem>
<problem date="5/3/2000" time="64.00000000000000">
 POTENTIAL IN WELL OP_1     NOT CONVERGED IN  1 X  50 ITERATIONS         
 RESIDUAL ERROR IN FLOWS AND PRESSURE                                    
   OIL         3.93603E+02                                               
   WATER       9.71067E-03                                               
   GAS         7.24229E+04                                               
  MSW PRES     1.49355E+02                                               
 TRY SETTING ITEM 2 IN THE WPOTCALC KEYWORD.                             
 TRY CHANGING PARAMETERS IN THE WSEGITER KEYWORD                         
</problem>
<problem date="10/3/2000" time="69.00000000000000">
 POTENTIAL IN WELL OP_1     NOT CONVERGED IN  1 X  50 ITERATIONS         
 RESIDUAL ERROR IN FLOWS AND PRESSURE                                    
   OIL         4.53223E+02                                               
   WATER       1.07695E-02                                               
   GAS         8.33929E+04                                               
  MSW PRES     1.40297E+02                                               
 TRY SETTING ITEM 2 IN THE WPOTCALC KEYWORD.                             
 TRY CHANGING PARAMETERS IN THE WSEGITER KEYWORD                         
</problem>
<problem date="15/3/2000" time="74.00000000000000">
 POTENTIAL IN WELL OP_1     NOT CONVERGED IN  1 X  50 ITERATIONS         
 RESIDUAL ERROR IN FLOWS AND PRESSURE                                    
   OIL         8.71156E+02                                               
   WATER       1.72767E-02                                               
   GAS         1.60293E+05                                               
  MSW PRES     1.25792E+02                                               
 TRY SETTING ITEM 2 IN THE WPOTCALC KEYWORD.                             
 TRY CHANGING PARAMETERS IN THE WSEGITER KEYWORD                         
</problem>
<problem date="20/3/2000" time="79.00000000000000">
 POTENTIAL IN WELL OP_1     NOT CONVERGED IN  1 X  50 ITERATIONS         
 RESIDUAL ERROR IN FLOWS AND PRESSURE                                    
   OIL         1.45200E+03                                               
   WATER       2.63811E-02                                               
   GAS         2.67169E+05                                               
  MSW PRES     1.05074E+02                                               
 TRY SETTING ITEM 2 IN THE WPOTCALC KEYWORD.                             
 TRY CHANGING PARAMETERS IN THE WSEGITER KEYWORD                         
</problem>
<problem date="25/3/2000" time="84.00000000000000">
 POTENTIAL IN WELL OP_1     NOT CONVERGED IN  1 X  50 ITERATIONS         
 RESIDUAL ERROR IN FLOWS AND PRESSURE                                    
   OIL         1.39564E+03                                               
   WATER       2.70024E-02                                               
   GAS         2.56798E+05                                               
  MSW PRES     1.11134E+02                                               
 TRY SETTING ITEM 2 IN THE WPOTCALC KEYWORD.                             
 TRY CHANGING PARAMETERS IN THE WSEGITER KEYWORD                         
</problem>
<problem date="28/3/2000" time="87.50000000000000">
 POTENTIAL IN WELL OP_1     NOT CONVERGED IN  1 X  50 ITERATIONS         
 RESIDUAL ERROR IN FLOWS AND PRESSURE                                    
   OIL         1.38947E+03                                               
   WATER       2.71936E-02                                               
   GAS         2.55663E+05                                               
  MSW PRES     1.11096E+02                                               
 TRY SETTING ITEM 2 IN THE WPOTCALC KEYWORD.                             
 TRY CHANGING PARAMETERS IN THE WSEGITER KEYWORD                         
</problem>
<problem date="1/4/2000" time="91.00000000000000">
 POTENTIAL IN WELL OP_1     NOT CONVERGED IN  1 X  50 ITERATIONS         
 RESIDUAL ERROR IN FLOWS AND PRESSURE                                    
   OIL         3.33913E+03                                               
   WATER       8.36952E-02                                               
   GAS         6.14400E+05                                               
  MSW PRES     2.29100E+02                                               
 TRY SETTING ITEM 2 IN THE WPOTCALC KEYWORD.                             
 TRY CHANGING PARAMETERS IN THE WSEGITER KEYWORD                         
</problem>
<problem date="2/4/2000" time="92.00000000000000">
 POTENTIAL IN WELL OP_1     NOT CONVERGED IN  1 X  50 ITERATIONS         
 RESIDUAL ERROR IN FLOWS AND PRESSURE                                    
   OIL         7.52068E+02                                               
   WATER       1.86656E-02                                               
   GAS         1.38380E+05                                               
  MSW PRES     1.38144E+02                                               
 TRY SETTING ITEM 2 IN THE WPOTCALC KEYWORD.                             
 TRY CHANGING PARAMETERS IN THE WSEGITER KEYWORD                         
</problem>
<problem date="5/4/2000" time="95.00000000000000">
 POTENTIAL IN WELL OP_1     NOT CONVERGED IN  1 X  50 ITERATIONS         
 RESIDUAL ERROR IN FLOWS AND PRESSURE                                    
   OIL         4.26803E+02                                               
   WATER       1.07513E-02                                               
   GAS         7.85317E+04                                               
  MSW PRES     1.42180E+02                                               
 TRY SETTING ITEM 2 IN THE WPOTCALC KEYWORD.                             
 TRY CHANGING PARAMETERS IN THE WSEGITER KEYWORD                         
</problem>
<problem date="10/4/2000" time="100.00000000000000">
 POTENTIAL IN WELL OP_1     NOT CONVERGED IN  1 X  50 ITERATIONS         
 RESIDUAL ERROR IN FLOWS AND PRESSURE                                    
   OIL         4.36608E+02                                               
   WATER       1.10337E-02                                               
   GAS         8.03359E+04                                               
  MSW PRES     1.41959E+02                                               
 TRY SETTING ITEM 2 IN THE WPOTCALC KEYWORD.                             
 TRY CHANGING PARAMETERS IN THE WSEGITER KEYWORD                         
</problem>
<problem date="15/4/2000" time="105.00000000000000">
 POTENTIAL IN WELL OP_1     NOT CONVERGED IN  1 X  50 ITERATIONS         
 RESIDUAL ERROR IN FLOWS AND PRESSURE                                    
   OIL         4.46529E+02                                               
   WATER       1.13208E-02                                               
   GAS         8.21613E+04                                               
  MSW PRES     1.41756E+02                                               
 TRY SETTING ITEM 2 IN THE WPOTCALC KEYWORD.                             
 TRY CHANGING PARAMETERS IN THE WSEGITER KEYWORD                         
</problem>
<problem date="20/4/2000" time="110.00000000000000">
 POTENTIAL IN WELL OP_1     NOT CONVERGED IN  1 X  50 ITERATIONS         
 RESIDUAL ERROR IN FLOWS AND PRESSURE                                    
   OIL         4.56591E+02                                               
   WATER       1.16135E-02                                               
   GAS         8.40127E+04                                               
  MSW PRES     1.41570E+02                                               
 TRY SETTING ITEM 2 IN THE WPOTCALC KEYWORD.                             
 TRY CHANGING PARAMETERS IN THE WSEGITER KEYWORD                         
</problem>
<problem date="25/4/2000" time="115.00000000000000">
 POTENTIAL IN WELL OP_1     NOT CONVERGED IN  1 X  50 ITERATIONS         
 RESIDUAL ERROR IN FLOWS AND PRESSURE                                    
   OIL         1.15931E+03                                               
   WATER       2.63545E-02                                               
   GAS         2.13313E+05                                               
  MSW PRES     1.22527E+02                                               
 TRY SETTING ITEM 2 IN THE WPOTCALC KEYWORD.                             
 TRY CHANGING PARAMETERS IN THE WSEGITER KEYWORD                         
</problem>
<problem date="28/4/2000" time="118.00000000000000">
 POTENTIAL IN WELL OP_1     NOT CONVERGED IN  1 X  50 ITERATIONS         
 RESIDUAL ERROR IN FLOWS AND PRESSURE                                    
   OIL         9.03006E+02                                               
   WATER       2.30587E-02                                               
   GAS         1.66153E+05                                               
  MSW PRES     1.58888E+02                                               
 TRY SETTING ITEM 2 IN THE WPOTCALC KEYWORD.                             
 TRY CHANGING PARAMETERS IN THE WSEGITER KEYWORD                         
</problem>
<problem date="1/5/2000" time="121.00000000000000">
 POTENTIAL IN WELL OP_1     NOT CONVERGED IN  1 X  50 ITERATIONS         
 RESIDUAL ERROR IN FLOWS AND PRESSURE                                    
   OIL         2.51230E+03                                               
   WATER       6.03946E-02                                               
   GAS         4.62263E+05                                               
  MSW PRES     1.20280E+02                                               
 TRY SETTING ITEM 2 IN THE WPOTCALC KEYWORD.                             
 TRY CHANGING PARAMETERS IN THE WSEGITER KEYWORD                         
</problem>
<problem date="2/5/2000" time="122.00000000000000">
 POTENTIAL IN WELL OP_1     NOT CONVERGED IN  1 X  50 ITERATIONS         
 RESIDUAL ERROR IN FLOWS AND PRESSURE                                    
   OIL         1.14793E+03                                               
   WATER       2.65581E-02                                               
   GAS         2.11220E+05                                               
  MSW PRES     1.22825E+02                                               
 TRY SETTING ITEM 2 IN THE WPOTCALC KEYWORD.                             
 TRY CHANGING PARAMETERS IN THE WSEGITER KEYWORD                         
</problem>
<problem date="5/5/2000" time="125.00000000000000">
 POTENTIAL IN WELL OP_1     NOT CONVERGED IN  1 X  50 ITERATIONS         
 RESIDUAL ERROR IN FLOWS AND PRESSURE                                    
   OIL         1.38848E+03                                               
   WATER       2.87719E-02                                               
   GAS         2.55481E+05                                               
  MSW PRES     1.03490E+02                                               
 TRY SETTING ITEM 2 IN THE WPOTCALC KEYWORD.                             
 TRY CHANGING PARAMETERS IN THE WSEGITER KEYWORD                         
</problem>
<problem date="10/5/2000" time="130.00000000000000">
 POTENTIAL IN WELL OP_1     NOT CONVERGED IN  1 X  50 ITERATIONS         
 RESIDUAL ERROR IN FLOWS AND PRESSURE                                    
   OIL         1.38183E+03                                               
   WATER       2.89732E-02                                               
   GAS         2.54257E+05                                               
  MSW PRES     1.03381E+02                                               
 TRY SETTING ITEM 2 IN THE WPOTCALC KEYWORD.                             
 TRY CHANGING PARAMETERS IN THE WSEGITER KEYWORD                         
</problem>
<problem date="15/5/2000" time="135.00000000000000">
 POTENTIAL IN WELL OP_1     NOT CONVERGED IN  1 X  50 ITERATIONS         
 RESIDUAL ERROR IN FLOWS AND PRESSURE                                    
   OIL         1.37518E+03                                               
   WATER       2.91658E-02                                               
   GAS         2.53033E+05                                               
  MSW PRES     1.03280E+02                                               
 TRY SETTING ITEM 2 IN THE WPOTCALC KEYWORD.                             
 TRY CHANGING PARAMETERS IN THE WSEGITER KEYWORD                         
</problem>
<problem date="20/5/2000" time="140.00000000000000">
 POTENTIAL IN WELL OP_1     NOT CONVERGED IN  1 X  50 ITERATIONS         
 RESIDUAL ERROR IN FLOWS AND PRESSURE                                    
   OIL         1.36852E+03                                               
   WATER       2.93503E-02                                               
   GAS         2.51807E+05                                               
  MSW PRES     1.03189E+02                                               
 TRY SETTING ITEM 2 IN THE WPOTCALC KEYWORD.                             
 TRY CHANGING PARAMETERS IN THE WSEGITER KEYWORD                         
</problem>
<problem date="25/5/2000" time="145.00000000000000">
 POTENTIAL IN WELL OP_1     NOT CONVERGED IN  1 X  50 ITERATIONS         
 RESIDUAL ERROR IN FLOWS AND PRESSURE                                    
   OIL         1.15250E+03                                               
   WATER       2.70091E-02                                               
   GAS         2.12060E+05                                               
  MSW PRES     1.18062E+02                                               
 TRY SETTING ITEM 2 IN THE WPOTCALC KEYWORD.                             
 TRY CHANGING PARAMETERS IN THE WSEGITER KEYWORD                         
</problem>
<problem date="28/5/2000" time="148.50000000000000">
 POTENTIAL IN WELL OP_1     NOT CONVERGED IN  1 X  50 ITERATIONS         
 RESIDUAL ERROR IN FLOWS AND PRESSURE                                    
   OIL         8.52053E+02                                               
   WATER       2.22146E-02                                               
   GAS         1.56778E+05                                               
  MSW PRES     1.53282E+02                                               
 TRY SETTING ITEM 2 IN THE WPOTCALC KEYWORD.                             
 TRY CHANGING PARAMETERS IN THE WSEGITER KEYWORD                         
</problem>
<message date="1/6/2000" time="152.00000000000000">
 OPENING WELL WI_2     AT TIME    152.00   DAYS                          
 CONTROLLED BY WATER RATE                                                
</message>
<message date="1/1/2001" time="366.00000000000000">
 RESTART FILE WRITTEN   REPORT    12                                     
 RESTART INCLUDES FLUIDS IN PLACE                                        
</message>
<message date="1/1/2001" time="366.00000000000000">
 OPENING WELL OP_4     AT TIME    366.00   DAYS                          
 CONTROLLED BY RESERVOIR FLUID VOLUME RATE                               
</message>
<message date="1/1/2001" time="366.00000000000000">
 OPENING WELL OP_5     AT TIME    366.00   DAYS                          
 CONTROLLED BY RESERVOIR FLUID VOLUME RATE                               
</message>
<problem date="1/1/2001" time="366.00000000000000">
 POTENTIAL IN WELL OP_5     NOT CONVERGED IN  1 X  50 ITERATIONS         
 RESIDUAL ERROR IN FLOWS AND PRESSURE                                    
   OIL         1.36478E+03                                               
   WATER       1.70670E-01                                               
   GAS         2.51119E+05                                               
  MSW PRES     6.98677E+01                                               
 TRY SETTING ITEM 2 IN THE WPOTCALC KEYWORD.                             
 TRY CHANGING PARAMETERS IN THE WSEGITER KEYWORD                         
</problem>
<message date="1/3/2001" time="425.00000000000000">
 OPENING WELL WI_3     AT TIME    425.00   DAYS                          
 CONTROLLED BY WATER RATE                                                
</message>
<message date="1/1/2002" time="731.00000000000000">
 RESTART FILE WRITTEN   REPORT    24                                     
 RESTART INCLUDES FLUIDS IN PLACE                                        
</message>
<message date="1/1/2003" time="1096.00000000000000">
 RESTART FILE WRITTEN   REPORT    36                                     
 RESTART INCLUDES FLUIDS IN PLACE                                        
</message>
<message date="1/1/2003" time="1096.00000000000000">
 SAVE TYPE RESTART FILE WRITTEN   REPORT    36                           
</message>
</eclipse>
