# This is an example configuration file for the test data set in 01_drogon_ccs
# Note: Need to replace the file paths

title: CO2 Leakage - Test example

shared_settings:
  scratch_ensembles:
    ens: "/home/sek/dev/webviz-subsurface-testdata-as/01_drogon_ccs/realization-[0-4]/iter-0"

# wellfile: &wellfile /home/sek/dev/webviz-subsurface-testdata-as/01_drogon_ccs/realization-0/iter-0/share/results/wells/well_picks.csv

layout:
 - page: "CO2Leakage"
   content:
     - CO2Leakage:
         ensembles:
           - ens
         plume_mass_relpath: "share/results/tables/plume_mass.csv"
         plume_actual_volume_relpath: "share/results/tables/plume_actual_volume.csv"
         boundary_settings:
            polygon_file_pattern: "share/results/polygons/*.csv"
            attribute: "boundary"
            hazardous_name: "hazardous"
            containment_name: "containment"
         fault_polygon_attribute: "gl_faultlines_extract_postprocess"
         well_pick_file: share/results/wells/well_picks.csv
         initial_surface: "topvolantis"
         map_attribute_names:
           MAX_SGAS: "max_sgas"
           MAX_AMFG: "max_amfg"
           MIGRATION_TIME_SGAS: "migrationtime_sgas"
           MIGRATION_TIME_AMFG: "migrationtime_amfg"
           MASS: "co2-mass-total"
           DISSOLVED: "co2-mass-aqu-phase" 
           FREE: "co2-mass-gas-phase" 
