<eclipse>
<message date="1/1/2000" time="0.00000000000000">
 CHECKING FOR LICENSES                                                   
</message>
<message date="1/1/2000" time="0.00000000000000">
 CHECKING FOR LICENSES                                                   
</message>
<message date="1/1/2000" time="0.00000000000000">
 THE MEMORY REQUIRED TO PROCESS THE GRID SECTION IS                      
      17002 KBYTES                                                       
</message>
<warning date="1/1/2000" time="0.00000000000000">
 INCLUDED FILE APPEARS TO BE A GRID FILE                                 
 GRID FILES MUST BE IMPORTED USING GDFILE OR IMPORT                      
</warning>
<warning date="1/1/2000" time="0.00000000000000">
 FLUX FLAG SET IN RUNSPEC BUT FLUXNUM KEYWORD                            
 NOT USED -- SAVE SPACE BY SETTING NTFREG = 0                            
 IN RUNSPEC KEYWORD REGDIMS.                                             
</warning>
<message date="1/1/2000" time="0.00000000000000">
 NEITHER OLDTRAN,OLDTRANR NOR NEWTRAN SPECIFIED                          
 TRANSMISSIBILITIES TO BE CALCULATED                                     
 USING  NEWTRAN                                                          
</message>
<message date="1/1/2000" time="0.00000000000000">
        3 NON-NEIGHBOUR CONNECTIONS HAVE BEEN IGNORED                    
 AS THEIR TRANSMISSIBILITY IS LESS THAN 0.100000E-05                     
</message>
<message date="1/1/2000" time="0.00000000000000">
 3228 NON-NEIGHBOUR CONNECTIONS PRESENT                                  
</message>
<comment date="1/1/2000" time="0.00000000000000">
 LEFT HANDED GRIDS MAY NOT BE SUPPORTED                                  
  IN ALL PRE AND POST PROCESSORS                                         
</comment>
<comment date="1/1/2000" time="0.00000000000000">
 THE GRID APPEARS TO BE LEFT HANDED, BUT                                 
 IS SPECIFIED IN GDORIENT AS RIGHT HANDED.                               
 ENSURE GDORIENT IS CORRECTLY DEFINED.                                   
</comment>
<message date="1/1/2000" time="0.00000000000000">
 NUMBER OF ACTIVE CELLS IS 35832                                         
</message>
<message date="1/1/2000" time="0.00000000000000">
 THE MEMORY REQUIRED TO PROCESS THE SOLUTION SECTION IS                  
     631565 KBYTES                                                       
</message>
<message date="1/1/2000" time="0.00000000000000">
    89918 CHARACTER VARIABLES USED                                       
</message>
<warning date="1/1/2000" time="0.00000000000000">
 ALTHOUGH ROCK DATA WAS ASSOCIATED WITH ROCKNUM                          
 THE NUMBER OF REGIONS WAS NOT EXPLICITLY SET                            
 USING ARGUMENT 13 OF KEYWORD TABDIMS                                    
 ROCK WILL BE ASSOCIATED WITH PVTNUM INSTEAD                             
</warning>
<warning date="1/1/2000" time="0.00000000000000">
 THE PROCESSED PVTO DATA FOR TABLE   1                                   
 HAS UNDERSATURATED BO LINES THAT WILL INTERSECT                         
 IF EXTRAPOLATED                                                         
 AT RS VALUES OF     522.8400  SM3/SM3 AND     630.0000  SM3/SM3         
 AND A PRESSURE OF       745.57   BARSA                                  
</warning>
<warning date="1/1/2000" time="0.00000000000000">
 THE PROCESSED PVTO DATA FOR TABLE   1                                   
 HAS UNDERSATURATED BO LINES THAT WILL INTERSECT                         
 IF EXTRAPOLATED                                                         
 AT RS VALUES OF     522.8400  SM3/SM3 AND     630.0000  SM3/SM3         
 AND A PRESSURE OF       745.99   BARSA                                  
</warning>
<warning date="1/1/2000" time="0.00000000000000">
 THE MAXIMUM PRESSURE ENTERED IN THE PVT TABLES                          
 FOR THE OIL PHASE IS    700.100. THIS IS GREATER THAN                   
 THE MAXIMUM PRESSURE FOR THE GAS PHASE,    700.000                      
 AND MAY LEAD TO PVT TABLE EXTRAPOLATION                                 
</warning>
<message date="1/1/2000" time="0.00000000000000">
 SAVE FILE HAS BEEN WRITTEN.                                             
</message>
<warning date="1/1/2000" time="0.00000000000000">
 THE FINE GRID BLOCK EQUILIBRATION SHOULD NOT                            
 USUALLY BE USED WITH THE SWATINIT KEYWORD AS                            
 THE INTEGRATED SOLUTION WILL NOT IN GENERAL                             
 HONOUR THE SWATINIT DATA.                                               
 FOR EQUILIBRATION REGION 1                                              
</warning>
<warning date="1/1/2000" time="0.00000000000000">
 THE FINE GRID BLOCK EQUILIBRATION SHOULD NOT                            
 USUALLY BE USED WITH THE SWATINIT KEYWORD AS                            
 THE INTEGRATED SOLUTION WILL NOT IN GENERAL                             
 HONOUR THE SWATINIT DATA.                                               
 FOR EQUILIBRATION REGION 2                                              
</warning>
<message date="1/1/2000" time="0.00000000000000">
 DRSDT OR DRSDTR KEYWORDS HAVE NOT BEEN                                  
 ENTERED, SO THE MAXIMUM GAS RE-SOLUTION                                 
 RATE IS DEFAULTED TO INFINITY.                                          
</message>
<message date="1/1/2000" time="0.00000000000000">
 RESTART FILE WRITTEN   REPORT     0                                     
 RESTART INCLUDES FLUIDS IN PLACE                                        
</message>
<error date="1/2/2000" time="31.00000000000000">
 SEGMENT   6 IN WELL OP_2     HAS A LENGTH &lt;OR= 0.0                   
</error>
<error date="1/2/2000" time="31.00000000000000">
</error>
<error date="1/2/2000" time="31.00000000000000">
 RUN STOPPED BECAUSE NUMBER OF   ERRORS                                  
 EXCEEDS MAXIMUM PERMITTED VALUE (     0).                               
 SEE MESSAGES KEYWORD                                                    
</error>
</eclipse>
